# Generated by Django 4.2 on 2023-07-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='date_to_do',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
