# Generated by Django 4.2 on 2023-07-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_author_task_user_alter_task_date_to_do'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_to_do',
        ),
    ]
